/**
 * Common constants for all features.
 */
/**
 * Breakpoint sm.
 */
export const BREAKPOINTS_SM_NAME: string = 'sm';

/**
 * Breakpoint md.
 */
export const BREAKPOINTS_MD_NAME: string = 'md';

/**
 * Breakpoint lg.
 */
export const BREAKPOINTS_LG_NAME: string = 'lg';

/**
 * Breakpoint xl.
 */
export const BREAKPOINTS_XL_NAME: string = 'xl';

/**
 * The value of tab vertical in sm device.
 */
export const TAB_SM_VERTICAL: boolean = false;

/**
 * The value of tab vertical in md device.
 */
export const TAB_MD_VERTICAL: boolean = false;

/**
 * The value of tab vertical in lg device.
 */
export const TAB_LG_VERTICAL: boolean = true;

/**
 * The value of tab vertical in xl device.
 */
export const TAB_XL_VERTICAL: boolean = true;

/**
 * The percentage of width of tab bar in sm device.
 */
export const TAB_SM_BAR_WIDTH: string = '100%';

/**
 * The percentage of width of tab bar in md device.
 */
export const TAB_MD_BAR_WIDTH: string = '100%';

/**
 * The width of tab bar in lg device.
 */
export const TAB_LG_BAR_WIDTH: string = '96vp';

/**
 * The width of tab bar in xl device.
 */
export const TAB_XL_BAR_WIDTH: string = '96vp';

/**
 * The height of tab bar in sm device.
 */
export const TAB_SM_BAR_HEIGHT: string = '56vp';

/**
 * The height of tab bar in md device.
 */
export const TAB_MD_BAR_HEIGHT: string = '56vp';

/**
 * The percentage of height tab bar in lg device.
 */
export const TAB_LG_BAR_HEIGHT: string = '60%';

/**
 * The percentage of height tab bar in xl device.
 */
export const TAB_XL_BAR_HEIGHT: string = '60%';

/**
 * The percentage of width of tab content.
 */
export const TAB_CONTENT_WIDTH: string = '100%';

/**
 * The percentage of height of tab content.
 */
export const TAB_CONTENT_HEIGHT: string = '100%';

/**
 * The percentage of width of flex component.
 */
export const FLEX_TAB_BAR_WIDTH: string = '100%';

/**
 * The percentage of height of flex component.
 */
export const FLEX_TAB_BAR_HEIGHT: string = '100%';

/**
 * The percentage of height in row component.
 */
export const FIRST_TAB_CHOOSE_INDEX: number = 0;

/**
 * The percentage of height in row component.
 */
export const COLUMN_HEIGHT: string = '100%';

/**
 * The number of tab component.
 */
export const TAB_SIZE: number = 4;

/**
 * The number of grid item.
 */
export const GRID_SIZE: number = 8;

/**
 * Initialize device breakpoints.
 */
export const BREAKPOINTS_INITIALIZE_NAME: string = 'md';

/**
 *  The value of aspect ratio in column component.
 */
export const COLUMN_ASPECT_RATIO: number = 16 / 9;

/**
 * Font weight of text component.
 */
export const COLUMN_TEXT_FONT_WEIGHT: number = 400;

/**
 *  The percentage of width of row component.
 */
export const ROW_WIDTH: string = '100%';

/**
 * The value of  attribute of columnsTemplate in sm device.
 */
export const SM_COL_TEMPLATE: string = '1fr 1fr';

/**
 * The value of  attribute of columnsTemplate in md device.
 */
export const MD_COL_TEMPLATE: string = '1fr 1fr 1fr';

/**
 * The value of  attribute of columnsTemplate in lg device.
 */
export const LG_COL_TEMPLATE: string = '1fr 1fr 1fr 1fr';

/**
 * The value of  attribute of columnsTemplate in xl device.
 */
export const XL_COL_TEMPLATE: string = '1fr 1fr 1fr 1fr';

/**
 * Initialization of attribute columnsTemplate.
 */
export const INITIALIZE_TEMPLATE: string = '1fr 1fr';

/**
 * Breakpoint name.
 */
export const BREAKPOINT_SYSTEM_NAME: string = 'mainBreakpoint';