/**
 * Common constants for all features.
 */
/**
 * Breakpoint sm.
 */
export const BREAKPOINTS_SM_NAME: string = 'sm';

/**
 * Breakpoint md.
 */
export const BREAKPOINTS_MD_NAME: string = 'md';

/**
 * Breakpoint lg.
 */
export const BREAKPOINTS_LG_NAME: string = 'lg';

/**
 * Breakpoint xl.
 */
export const BREAKPOINTS_XL_NAME: string = 'xl';

/**
 * The break point value of sm device.
 */
export const BREAKPOINTS_SM_SIZE: number = 0;

/**
 * The break point value of md device.
 */
export const BREAKPOINTS_MD_SIZE: number = 600;

/**
 * The break point value of lg device.
 */
export const BREAKPOINTS_LG_SIZE: number = 840;

/**
 * The break point value of xl device.
 */
export const BREAKPOINTS_XL_SIZE: number = 1320;

/**
 * Initialize device breakpoints.
 */
export const BREAKPOINTS_INITIALIZE_NAME: string = 'md';

/**
 * Initialize device breakpoint Id.
 */
export const BREAKPOINT_ID_INITIALIZE_NAME: string = 'unknown';