/**
 * Common constants for all features.
 */
/**
 * The percentage of width in row component.
 */
export const COLUMN_WIDTH: string = '100%';

/**
 * The percentage of height in row component.
 */
export const COLUMN_HEIGHT: string = '100%';

/**
 * The value of number of the flex shrink.
 */
export const COLUMN_FLEX_SHRINK: number = 1;

/**
 * The percentage of width.
 */
export const WIDTH: string = '100%';

/**
 * The percentage of height.
 */
export const HEIGHT: string = '100%';

/**
 * The minimum rolling value of the slider.
 */
export const SLIDER_MIN: number = 55;

/**
 * The maximum rolling value of the slider.
 */
export const SLIDER_MAX: number = 90;

/**
 * The margin between the slider and the bottom.
 */
export const SLIDER_MARGIN: number = 24;

/**
 * The percent sign.
 */
export const PERCENT_SIGN: string = '%';