/**
 * Common constants for all features.
 */
/**
 * The number of columns for XS device.
 */
export const COLUMN_XS: number = 4;

/**
 * The number of columns for SM device.
 */
export const COLUMN_SM: number = 4;

/**
 * The number of columns for MD device.
 */
export const COLUMN_MD: number = 8;

/**
 * The number of columns for LG device.
 */
export const COLUMN_LG: number = 12;

/**
 * The number of span for XS device.
 */
export const SPAN_XS: number = 4;

/**
 * The number of span for SM device.
 */
export const SPAN_SM: number = 4;

/**
 * The number of span for MD device.
 */
export const SPAN_MD: number = 4;

/**
 * The number of span for LG device.
 */
export const SPAN_LG: number = 4;

/**
 * The number of offset for XS device.
 */
export const OFFSET_XS: number = 0;

/**
 * The number of offset for SM device.
 */
export const OFFSET_SM: number = 0;

/**
 * The number of offset for MD device.
 */
export const OFFSET_MD: number = 2;

/**
 * The number of offset for LG device.
 */
export const OFFSET_LG: number = 4;

/**
 * Font weight of the list.
 */
export const LIST_FONT_WEIGHT: number = 500;

/**
 *Width of the list.
 */
export const LIST_WIDTH: string = '100%';

/**
 * The percentage of width of the list item.
 */
export const LIST_ITEM_WIDTH: string = '100%';

/**
 * The percentage of height of the column.
 */
export const COLUMN_HEIGHT: string = '100%';

/**
 * The name of the bundleName.
 */
export const BUNDLE_NAME: string = 'com.goodhub.immich';

/**
 * The name of the abilityName.
 */
export const ABILITY_NAME: string = 'ResponsiveLayoutItemAbility';

/**
 * Initialize device breakpoints.
 */
export const BREAKPOINTS_INITIALIZE_NAME: string = 'md';

/**
 * Localization ability.
 */
export const LOCATION_CAPABILITY: string = 'SystemCapability.Location.Location.Core';

/**
 * Breakpoint name.
 */
export const BREAKPOINT_SYSTEM_NAME: string = 'mainBreakpoint';

/**
 * The percentage of height of column component.
 */
export const SYSTEM_COLUMN_HEIGHT: string = '100%';

/**
 * The percentage of width of column component.
 */
export const SYSTEM_COLUMN_WIDTH: string = '100%';

/**
 * The percentage of width of row component.
 */
export const SYSTEM_ROW_WIDTH: string = '100%';

/**
 * Font weight of text component.
 */
export const TEXT_FONT_WEIGHT: number = 500;

/**
 * The percentage of width of column component.
 */
export const ADAPTIVE_COLUMN_WIDTH: string = '100%';

/**
 * The percentage of height of column component.
 */
export const ADAPTIVE_COLUMN_HEIGHT: string = '100%';

/**
 * The percentage of height of column component.
 */
export const ADAPTIVE_FLEXIBLE_COLUMN_WIDTH: string = '100%';

/**
 * The value of shrink of column component.
 */
export const ADAPTIVE_FLEX_SHRINK: number = 1;

/**
 * Animation duration.
 */
export const ANIMATION_DURATION: number = 300;
